// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120050116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.SchedulingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxDailyHours")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("int");

                    b.Property<int>("MinRestPeriodHours")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeThresholdWeeklyHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SchedulingRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxDailyHours = 9,
                            MaxWeeklyHours = 45,
                            MinRestPeriodHours = 12,
                            OvertimeThresholdWeeklyHours = 50
                        });
                });

            modelBuilder.Entity("api.Models.ShiftInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RequiredHeadcountOverride")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTemplateId");

                    b.ToTable("ShiftInstances");
                });

            modelBuilder.Entity("api.Models.ShiftTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiredHeadcount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ShiftTemplates");
                });

            modelBuilder.Entity("api.Models.ShiftInstance", b =>
                {
                    b.HasOne("api.Models.ShiftTemplate", "ShiftTemplate")
                        .WithMany()
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
